### ISSUE TITLE
Document --edgerc and --section parameters in help

### ISSUE THREAD

**Issue by javiergarza** [akamai/cli-firewall#10]
It will be great if the cli-firewall would be consistent with the rest of Akamai CLI packages and would allow the --edgerc flag to allow indicating the file containing the edgegrid credentials and --section flag to allow indicating the .edgerc section to use

**Comment by vreddhi** [comment]
It should already support both. I see it working.

**Comment by javiergarza** [comment]
OK, fair enough. 
1) Can you please include those 2 parameters in the online help?
2) In the other CLI packages those parameters are indicated after the package name, but in the fw package the command seems to fail when you indicate --edgerc or --section before the command (see second command below)
 
$ akamai fw help
usage: akamai firewall help [command] [--version]  ...

Akamai CLI for Firewall Rules

optional arguments:
  --version           show program's version number and exit

Commands:

    help              Show available help
    list-services     List all firewall rules services available
    list-subscriptions
                      List current subscriptions
    subscribe         Subscribe to a firewall rules service
    unsubscribe       Unsubscribe from a firewall rules service
    list-cidrs        List the CIDRs for current subscription or a specific
                      firewall rules service

$ akamai fw --section dac-open help
usage: akamai firewall [--version]  ...
akamai firewall: error: argument : invalid choice: 'dac-open' (choose from 'help', 'list-services', 'list-subscriptions', 'subscribe', 'unsubscribe', 'list-cidrs')

**Comment by aetsai** [comment]
closed in v0.2.0
