### ISSUE TITLE
Enhancement for list-cidrs command in site-shield module to show CurrentCidrs and Changs to Proposed.

### ISSUE THREAD

**Issue by yoyabu** [akamai/cli-firewall#13]
It's more useful if list-cidrs command in site-shield module to shows CurrentCidrs, and the delta (Added/Removed) of Proposed Cidrs. 

CurrentCidrs can be available in /siteshield/v1/maps/<mapID> endpoint as well.

**Comment by aetsai** [comment]
Hi, if you add the --json argument that should show the proposedCidrs and currentCidrs

Ex:
akamai ss list-cidrs --map-id xxxx --json

Is this sufficient?

**Comment by aetsai** [comment]
Closing as confirmed as using --json argument gets current and proposed cidrs
