### ISSUE TITLE
Error Installing Firewall Package

### ISSUE THREAD

**Issue by SilentWolf8979** [akamai/cli-firewall#2]
I'm seeing an error trying to install the firewall package.  Other packages (purge, appsec, property) installed fine.  I am behind a proxy, but adding the --proxy param with our proxy did not resolve the problem.

C:\>akamai install firewall
Attempting to fetch command from https://github.com/akamai/cli-firewall.git...... [OK]
Installing...... [FAIL]
Unable to run package manager: exit status 1

**Comment by SilentWolf8979** [comment]
I tried uninstalling Python and then reinstalling it.  That appears to have allowed me to successfully run the "akamai install firewall" command.  However I'm seeing it listed twice.

![image](https://user-images.githubusercontent.com/39505131/41607149-f1f40944-73aa-11e8-9683-4417223a3bd5.png)

I'm also not able to run the commands and am getting the below error:

C:\>akamai firewall help
Traceback (most recent call last):
  File "H:\.akamai-cli\src\cli-firewall\bin\akamai-firewall", line 29, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'

I don't see the cli-firewall folder in the same location as the other packages: C:\Users\userID\.akamai-cli\src

**Comment by vreddhi** [comment]
Can you give a fresh try? Looks like the first time it created the folder but failed to download due to some reason. And then a successful download resulted in duplicate entries.
